name: 'Check updates and build'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  packages: write

jobs:
  check:
    name: Check updates
    runs-on: ubuntu-latest
    outputs:
      VERSION_UPDATED: ${{ steps.check.outputs.VERSION_UPDATED }}
      VERSION: ${{ steps.check.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout files
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: check
        name: Run check script
        run: |
          chmod +x check.sh
          ./check.sh

      - uses: actions-js/push@master
        name: Commit & Push changes
        if: steps.check.outputs.VERSION_UPDATED == 1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "ci: pydio updated `${{ steps.check.outputs.VERSION }}`"

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.VERSION_UPDATED == 1
    steps:
      - uses: actions/checkout@v4
        name: Checkout files

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          build-args: VERSION=${{ needs.check.outputs.VERSION }}
          tags: |
            ghcr.io/pmh-only/pydio:latest
            ghcr.io/pmh-only/pydio:${{ needs.check.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
